### PR TITLE
Log additional information on XVFB start failure

### PR DESCRIPTION
**Pull request by peterdemin**

### CODE REVIEW

**Comment by cgoldberg** [comment]
Thanks for the PR!  

I just tested your code... and the substitutions in the error message are not working correctly.  when the exception is raised, it displays something like:

RuntimeError: ('Xvfb did not start (%r): %r', 1, ['Xvfb', ':1340128217', '-screen', '0', '800x680x24'])

I think we want it to look like this:

RuntimeError: Xvfb did not start (1): 'Xvfb :1340128217 -screen 0 800x680x24'

can you have a look and update your PR?

**Comment by peterdemin** [comment]
Ah, sorry, fixed that.

**Comment by cgoldberg** [comment]
cool.. that looks better.

one small nitpick:
for consistency, could you use format() instead of the old style % string formatting?

**Comment by cgoldberg** [comment]
thanks!  👍

**Comment by peterdemin** [comment]
You are welcome!

**Pull request merged**
